dist: trusty
language: node_js
sudo: false
git:
  depth: 5
node_js: 10
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

.env:
  github_keys: &github_keys
    - secure: 'kY77wKVJtgF1TdvVr6lmpljGAJ2JhChxAGCFJ8nXMGz6QC8/4uICR0J6GpRZxOHCqbyFiXcoaV/lzuyod9KpvvNGuM+GMnU732iAR60iKB8TYQN57up+kKjMXIM3+kw0grfuUYM2/GzqFugt5y52PnXQ573Yycl+glFuOc96L6dV/RuDz05WPU08X1YlvUMfX9adePEl7vSnVFp+p9QsylH5bIpitcL63h4G0fTL8bhekzSEMUlrKCabkHHbsiH4BYjfEwg3IOHWr0phcDjF6adMqGkcVjKTIkiXlesl8BeMMbkug6dMfKpIw3K0RQM8oG4TiGRB9kiV3jSr0XqS6SplgfLa2Zar003IW2dEbfEkf4h9uq4Imli+m4sIPzpClhNnDrTJcMPCsCI+9dWDdlFwFCNlmfFl9hGrLUs+kJAtz18Cp5NJa1h7oKAcYaa6R2zHTyg4EWTBy5KNvWs+6EZq8w+AtE0uePn7t8OYtxRX3YglRzoigSOc+EgmQk8ZEtZr78vQZQbxQi67LiFnzaSrEEykRdEW9CW5knd0QsW1LDJQz+a/kHo6x5jQ5v1RFUFlkFUdSu7WoqOJr0PYVLK+iRm8NTWDL0+/96KAcRP1MrkDAbvJgv0zQj0upYYww7bH7RK0JXw79C4/uBqPP4q060YW/knkAkfNFUCnFkE='
  npm_keys: &npm_keys
    - secure: 'Plusf4k5+btmykwKRwtgY0EODMNLh2FBgkEqtciHLLPIbWw2JjEppg3E3Q9n+lspr89FJgAblt99TXTYLUpbLeOMmlQrfSTR/UG60KgCVH6cB1iLztEz6iD+Q+B6p1MLhgJ3iPWbaDDxcgwcLY1cXWyFKh7agKlJkyPmJSF2q3FcKfSjBpDNg3oSW9Zwho3snyiSzun4wogv7I2jSI31Ne/yRCRnMtGnwepwUu55fZHPZeVNN42oxz/pIcd/h+DdNDFr9U4HsiHUTCmddQZ8JqnTELE7FXlUaB9ykir5A8ek8yr/m0TdABQl3YVOHSGHVf2sqGNXodB9uj8eNUcdR//VWojMvrLzO5gtvlZeTHgnTDjvgDibGOR16lYLPOGylYr5ckjaOQrHRYmwMWPlka/lG3zifRTxZzZG5v0e9+TgU5oAFWLqavEYQ36HhpK9CoMtDHukuMfaiuGRNbtz5W8FpCJT9Mp8LMq11eJTxjXSh9C+VUpCBQ33i/jcyFiZeqoeNlt3NToIfpUczLX4bHm8vSB2WoS3vj2imRXVvTTER8KTdgOCS1d5qVRlnf6/vJYcWjKpazJUqW8P1QT5G2/e/GwagdkY9FJB3kXMNHaJGa23DaNqeCl/Aqr3WoZISyLz7Jpa4qjATzdNGZUK7M3RqlKwWVdZR0LNNYFSd/w='

jobs:
  include:
    - stage: Release
      git:
        # NOTE(douglasduteil): disable git --depth
        # Try to have all the commits for the release Change Log
        # see travis-ci/travis-ci#3412
        depth: 9999999 # Over 9000 !
      install: yarn --frozen-lockfile
      env:
        - *github_keys
        - *npm_keys
      before_script:
        - npm config set access public
        - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        - git checkout ${TRAVIS_BRANCH}
        - git config user.name "Social Groovy Bot"
        - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
      script:
        - GH_TOKEN=${GITHUB_TOKEN} yarn lerna version ${LERNA_ARGS:=--no}
        - yarn lerna publish from-git --no
