dist: trusty
language: node_js
sudo: false
git:
  depth: 5
node_js: 10
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: Lint
      install: yarn --frozen-lockfile
      script: 
        - yarn lerna run --stream lint
        if: type != pull_request
          - yarn chromatic