dist: trusty
language: node_js
sudo: false
git:
  depth: 5
node_js: 10
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

stages:
  - name: Chromatic
    if: NOT type = pull_request
  - name: Chromatic Master
    if: (branch = master) AND (NOT (type IN (push, pull_request)))
    
jobs:
  include:
    - stage: Chromatic
      install: yarn --frozen-lockfile
      script: 
      - yarn chromatic
    - stage: Chromatic Master
      install: yarn --frozen-lockfile
      script: 
      - yarn chromatic --auto-accept-changes    